### ISSUE TITLE
Create a "hot reload" event handler for CI support

### ISSUE THREAD

**Issue by foxalfabravo** [CybercentreCanada/assemblyline-service-server#102]
When running integration tests from CI after a deployment from scratch, file analysis by service produces:
- correct result.section.body
- no heuristic section
- score is 0

From cccs-sgaron (https://discord.com/channels/908084610158714900/908717528082173983/981190642979991582) this is related to timing issues : service runs the analysis before the service_server has refreshed its heuristic list.

Analysis is correct in privileged mode

Could you implement a "force hot reload" route in service server so that CI can make sure all components have correct informations?

**Comment by cccs-douglass** [comment]
Would you feel this is resolved by fixing this other issue? CybercentreCanada/assemblyline-core#573

**Comment by foxalfabravo** [comment]
Yes, sorry I was in holidays, but I had almost the same fix to push, so it is resolved. I will provide more intel when using 118 release or later (with tiff correction)
